name: reirei
favicon: null
layout_spectrum: 0.08189015579409897
typography_spectrum: 0.4328473892528564
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.41905700881034136
  lightness: 0.46015796484425664
  saturation: 0.32893533166497946
  rhythmicContrast: 0.7340909386985004
purpose: []
